// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Article struct {
	ID         string `json:"id" bson:"_id"`
	Name       string `json:"name" bson:"name"`
	Definition string `json:"definition" bson:"definition"`
	Directory  string `json:"directory" bson:"directory"`
}

type NewArticle struct {
	Name       string `json:"name" bson:"name"`
	Definition string `json:"definition" bson:"definition"`
	Directory  string `json:"directory" bson:"directory"`
}

type NewTag struct {
	Name     string  `json:"name" bson:"name"`
	Category *string `json:"category" bson:"category"`
}

type Tag struct {
	ID            string  `json:"id" bson:"_id"`
	Name          string  `json:"name" bson:"name"`
	Category      *string `json:"category" bson:"category"`
	DispathWeight *int    `json:"dispathWeight" bson:"dispathWeight"`
}
